#!/bin/env sh

# Usage:
#	./run [OPTION...] FILE

CC="gcc -g -std=c99 -pedantic -W -Wall -Werror"
INPUT="input"
VALGRIND=false

while getopts ":stv" arg; do
	case "$arg" in
		s) CC="gcc -g" ;;
		t) INPUT="test" ;;
		v) VALGRIND=true ;;
		*) ;;
	esac
done

PROGRAM=$(eval echo "\$$OPTIND")

if ! echo "$PROGRAM" | grep -q -E '\.c'; then
	echo "Error: missing program"
	exit 1
fi

eval "$CC $PROGRAM strmanip.c memmanage.c -lm" && ./a.out < "$INPUT" && {
	if "$VALGRIND"; then
		head -n 1 > /dev/null
		valgrind -s --leak-check=full --track-origins=yes --max-stackframe=10000000 ./a.out < "$INPUT"
	fi
}
