#!/usr/bin/env sh

CC="gcc -g -std=c99 -pedantic -W -Wall -Werror -lm"
PROGRAM=""
INPUT="input"
VALGRIND=""

for arg in "$@"; do
	case "$arg" in
		*.c)
			PROGRAM="$arg"
			;;
		-t)
			INPUT="test"
			;;
		-v)
			;;
	esac
done

if [ -z PROGRAM ]; then
	echo "No program selected"
	exit 1
fi

eval "$CC $PROGRAM" &&
	eval "./a.out < $INPUT" &&
	head -n 1 > /dev/null &&
	eval "valgrind --leak-check=full ./a.out < $INPUT"
